### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by epinault** [bastilian/wunderlist-cli#2]
wunderlist -h
/Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-core-1.22.0/lib/fog/core/provider.rb:22:in `service': wrong number of arguments (3 for 2) (ArgumentError)
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:7:in`module:Wunderlist'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:5:in `<module:Fog>'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:4:in`<top (required)>'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/wunderlist-cli-0.0.1/lib/cli.rb:3:in `<top (required)>'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/wunderlist-cli-0.0.1/bin/wunderlist:4:in`<top (required)>'
    from /Users/Emmanuel/.gem/ruby/2.1.2/bin/wunderlist:23:in `load'
    from /Users/Emmanuel/.gem/ruby/2.1.2/bin/wunderlist:23:in`<main>'
Emmanuel-Pinaults-MacBook-Pro:~ Emmanuel$ wunderlist help
/Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-core-1.22.0/lib/fog/core/provider.rb:22:in `service': wrong number of arguments (3 for 2) (ArgumentError)
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:7:in`module:Wunderlist'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:5:in `<module:Fog>'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:4:in`<top (required)>'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/wunderlist-cli-0.0.1/lib/cli.rb:3:in `<top (required)>'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/wunderlist-cli-0.0.1/bin/wunderlist:4:in`<top (required)>'
    from /Users/Emmanuel/.gem/ruby/2.1.2/bin/wunderlist:23:in `load'
    from /Users/Emmanuel/.gem/ruby/2.1.2/bin/wunderlist:23:in`<main>'
Emmanuel-Pinaults-MacBook-Pro:~ Emmanuel$ wunderlist
/Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-core-1.22.0/lib/fog/core/provider.rb:22:in `service': wrong number of arguments (3 for 2) (ArgumentError)
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:7:in`module:Wunderlist'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:5:in `<module:Fog>'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:4:in`<top (required)>'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/wunderlist-cli-0.0.1/lib/cli.rb:3:in `<top (required)>'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/Emmanuel/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/Emmanuel/.gem/ruby/2.1.2/gems/wunderlist-cli-0.0.1/bin/wunderlist:4:in`<top (required)>'
    from /Users/Emmanuel/.gem/ruby/2.1.2/bin/wunderlist:23:in `load'
    from /Users/Emmanuel/.gem/ruby/2.1.2/bin/wunderlist:23:in`<main>'

**Comment by davidosomething** [comment]
+1

```
/Users/dtrakoun1271/.gem/ruby/2.1.3/gems/fog-core-1.24.0/lib/fog/core/provider.rb:22:in `service': wrong number of arguments (3 for 2) (ArgumentError)
    from /Users/dtrakoun1271/.gem/ruby/2.1.3/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:7:in `<module:Wunderlist>'
    from /Users/dtrakoun1271/.gem/ruby/2.1.3/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:5:in `<module:Fog>'
    from /Users/dtrakoun1271/.gem/ruby/2.1.3/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:4:in `<top (required)>'
    from /Users/dtrakoun1271/.rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/dtrakoun1271/.rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/dtrakoun1271/.gem/ruby/2.1.3/gems/wunderlist-cli-0.0.1/lib/cli.rb:3:in `<top (required)>'
    from /Users/dtrakoun1271/.rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/dtrakoun1271/.rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/dtrakoun1271/.gem/ruby/2.1.3/gems/wunderlist-cli-0.0.1/bin/wunderlist:4:in `<top (required)>'
    from /Users/dtrakoun1271/.gem/ruby/2.1.3/bin/wunderlist:23:in `load'
    from /Users/dtrakoun1271/.gem/ruby/2.1.3/bin/wunderlist:23:in `<main>'

```

**Comment by jcalonso** [comment]
same here

**Comment by martiningram** [comment]
Same issue here, too

**Comment by alejofloresnet** [comment]
$ wunderlist setup

/var/lib/gems/1.9.1/gems/fog-core-1.29.0/lib/fog/core/provider.rb:20:in `service': wrong number of arguments (3 for 2) (ArgumentError)
    from /var/lib/gems/1.9.1/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:7:in`module:Wunderlist'
    from /var/lib/gems/1.9.1/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:5:in `<module:Fog>'
    from /var/lib/gems/1.9.1/gems/fog-wunderlist-0.1/lib/fog/wunderlist.rb:4:in`<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.9.1/gems/wunderlist-cli-0.0.1/lib/cli.rb:3:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/wunderlist-cli-0.0.1/bin/wunderlist:4:in`<top (required)>'
    from /usr/local/bin/wunderlist:23:in `load'
    from /usr/local/bin/wunderlist:23:in`<main>'

yup

**Comment by webcultist** [comment]
Also here ^^

**Comment by epinault** [comment]
I think this project is dead. Also They have an official API https://developer.wunderlist.com/documentation. I am starting to work on a newer ruby version

**Comment by jessmartin** [comment]
@epinault Any progress on the new ruby version?

**Comment by epinault** [comment]
@jessmartin Sorry been a busy past couple of months for me. Will get something out soon (this week is looking good for me to get something out)
